import RestaurantNavBar from "../components/RestaurantNavBar";
import Menu from "../components/Menu";

export const metadata = {
  title: "Restaurant: Menu | Open Table",
  description: "Generated by create next app",
};

function RestaurantMenuPage() {
  return (
    <>
      <div className="bg-white w-[100%] rounded p-3 shadow">
        <RestaurantNavBar />
        <Menu />
      </div>
    </>
  );
}

export default RestaurantMenuPage;
