import RestaurantNavBar from "../components/RestaurantNavBar";
import Menu from "../components/Menu";
import { PrismaClient } from "@prisma/client";

export const metadata = {
  title: "Restaurant: Menu | Open Table",
  description: "Generated by create next app",
};

const prisma = new PrismaClient();

const fetchRestaurantMenu = async (slug: string) => {
  const restaurant = await prisma.restaurant.findUnique({
    where: {
      slug,
    },
    select: {
      items: true,
    },
  });

  if (!restaurant) {
    throw new Error();
  }

  return restaurant.items;
};

async function RestaurantMenuPage({ params }: { params: { name: string } }) {
  const menu = await fetchRestaurantMenu(params.name);
  return (
    <>
      <div className="bg-white w-[100%] rounded p-3 shadow">
        <RestaurantNavBar slug={params.name} />
        <Menu menu={menu} />
      </div>
    </>
  );
}

export default RestaurantMenuPage;
