import Header from "./components/Header";
import SearchSidebar from "./components/SearchSidebar";
import RestaurantCard from "./components/RestaurantCard";
import type { Metadata } from "next";
import { PRICE, PrismaClient } from "@prisma/client";

export const metadata: Metadata = {
  title: "Search | Open Table",
  description: "Generated by create next app",
};

const prisma = new PrismaClient();

const fetchRestaurantsByLocation = async (city?: string) => {
  const select = {
    id: true,
    name: true,
    main_image: true,
    location: true,
    price: true,
    cuisine: true,
    slug: true,
  };
  if (!city) return prisma.restaurant.findMany({ select });
  const restaurants = await prisma.restaurant.findMany({
    where: {
      location: {
        name: {
          equals: city?.toLocaleLowerCase(),
        },
      },
    },
    select,
  });
  return restaurants;
};

const fetchLocations = async () => {
  const locations = await prisma.location.findMany({
    select: {
      id: true,
      name: true,
    },
  });

  return locations;
};

const fetchCusines = async () => {
  const cuisines = await prisma.cuisine.findMany({
    select: {
      id: true,
      name: true,
    },
  });

  return cuisines;
};
async function SearchPage({
  searchParams,
}: {
  searchParams: { city?: string; cuisine?: string; price?: PRICE };
}) {
  const restaurants = await fetchRestaurantsByLocation(searchParams.city);
  const locations = await fetchLocations();
  const cuisines = await fetchCusines();
  return (
    <>
      <Header />
      <div className="flex py-4 m-auto w-2/3 justify-between items-start">
        <SearchSidebar
          locations={locations}
          cuisines={cuisines}
          searchParams={searchParams}
        />
        <div className="w-5/6">
          {restaurants.length ? (
            restaurants.map((restaurant) => (
              <RestaurantCard key={restaurant.id} restaurant={restaurant} />
            ))
          ) : (
            <p>Sorry, we found no restaurants in {searchParams.city}</p>
          )}
        </div>
      </div>
    </>
  );
}

export default SearchPage;
